### ISSUE TITLE
Cannot use this package

### ISSUE THREAD

**Issue by ChienKaiMa** [BRiAl/pyBRiAl#2]
I have downloaded this package from `Releases` page and typed `sudo python3 setup.py install`.
Installation seemed fine but I couldn't use it in Python.

![image](https://user-images.githubusercontent.com/37112053/100625508-99318080-335f-11eb-8dac-f0a3ef26dc50.png)

**Comment by kiwifb** [comment]
Yes, this repo should be a least archived if not deleted. You would need to install sagemath https://www.sagemath.org/ to be able to use it. And the code is now completely included in sagemath making this repository completely redundant.
